### ISSUE TITLE
Template doesn't work in 2020

### ISSUE THREAD

**Issue by hiteshhedwig** [npatta01/mobile-deep-learning-classifier#13]
I tried using the template just as it is. To see model deployment as an example for my other project. Sadly I cannot reproduce the results. It gives some really huge error while I connect with expo and start and I have no experience with Android development so this gives real pain. I would ask contributers of this project to guide me about this.

Issue: Template doesn't work in 2020. 

How to reproduce error: Clone the repository and follow the docs line by line. 

Note: I have successfully deployed web app after encountering minor errors. Don't know how to deal with mobile issue

**Comment by npatta01** [comment]
@hiteshhedwig can you give a try with the latest code
